source 'https://supermarket.chef.io'

metadata


cookbook 'chef-client'
cookbook 'sudo'
cookbook 'yum'
cookbook 'yum-epel'
cookbook 'omnibus_updater'
cookbook 'hostsfile'
cookbook 'gelf_handler'
cookbook 'chef_handler'
cookbook 'ntp'
cookbook 'build-essential'
cookbook 'locale'

